
.. _ex_coupled_function_obj_conf:

Tutorial case A08: "Building the configuration spreadsheet programatically"
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Based in the tutorial related with the :ref:`coupled function <ex_coupled_function_metamodel>`, in this tutorial is described how to build the configuration spreadsheet programatically using the :ref:`objconf()<pymetamodels_objconf>`. The analysis includes the sampling, metamodeling and optimization routines.

The code to print the data structure objects are described in the script as follows in **test_analysis.py**,

.. literalinclude:: /_examples/A08 coupled_function_obj_conf/test_analysis.py
    :linenos:
    :language: python
    :emphasize-lines: 45-62
    :caption: Coupled function test analysis. Objconf()
    :name: ex_coupled_function_test_analysis_obj_conf
