version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
   configuration: docs/conf.py
   builder: html
   fail_on_warning: false

python:
   install:
       - requirements: requirements_docs.txt
