
.. _ex_coupled_function_load_DOEs:

Tutorial case A09: "Loading DOEs from file, couple function case"
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Based in the tutorial related with the :ref:`coupled function <ex_coupled_function_metamodel>`, in this tutorial is described how to load tables of data as DOEX and DOEY input and outputs. The analysis includes the sampling, metamodeling and optimization routines.

The code to print the data structure objects are described in the script as follows in **test_analysis.py**,

.. literalinclude:: /_examples/A09 coupled_function_load_DOEs/test_analysis.py
    :linenos:
    :language: python
    :emphasize-lines: 85-86
    :caption: Coupled function test analysis. Loading DOEX and DOEY data.
    :name: ex_coupled_function_load_DOEs_data    
