
.. _conf_spreadsheet_struct_out-ach:

.. tabularcolumns:: | C | C | C | C | C | C | C | C | C |
.. list-table:: Main case output model variables description for the configuration spreadsheet
    :name: conf_spreadsheet_struct_out
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - variable
      - value
      - ud
      - comment
      - array
      - op_min
      - op_min=0
      - ineq_(>=0)
      - eq_(=0)
    * - Y1
      - None
      - m^3
      - function output
      - 0
      - 0
      - 0
      - 0
      - 0
    * - Y2
      - None
      - m^3
      - function output
      - 0
      - 1
      - 0
      - 0
      - 0
