
.. _conf_spreadsheet_struc-ach:

.. tabularcolumns:: | C | C | C | C | C | C |
.. list-table:: Main cases description for the configuration spreadsheet
    :name: conf_spreadsheet_struc
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - case
      - vars sheet
      - output sheet
      - samples
      - sensitivity method
      - comment
    * - case_1
      - case_1_vars_sensi
      - case_out
      - 50.0
      - RBD-Fast
      - 
