
.. _coupled_function_data_struct_ou-ach:

.. tabularcolumns:: | C | C | C | C | C |
.. list-table:: Main case output model variables description for the coupled function tutorial data structure
    :name: coupled_function_data_struct_ou
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - variable
      - value
      - ud
      - comment
      - array
    * - Y
      - None
      - m^3
      - function output
      - 0
