
.. _coupled_function_data_struct-ach:

.. tabularcolumns:: | C | C | C | C | C | C |
.. list-table:: Main cases description for the coupled function tutorial data structure
    :name: coupled_function_data_struct
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - case
      - vars sheet
      - output sheet
      - samples
      - sensitivity method
      - comment
    * - case_1
      - case_1_vars_sensi
      - case_out
      - 50.0
      - RBD-Fast
      - 
