
.. _coupled_func_case_0_vars_sensi-ach:

.. tabularcolumns:: | C | C | C | C | C | C | C | C | C | C | C | C |
.. list-table:: Main case input model variables description for the coupled function tutorial
    :name: coupled_func_case_0_vars_sensi
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - variable
      - value
      - min
      - max
      - distribution
      - is_range
      - cov_un
      - ud
      - alias
      - comment
      - constrain
      - comment
    * - X1
      - 1.0
      - -3.14
      - 3.14
      - unif
      - 1
      - 0.05
      - [-]
      - X1
      - None
      - 0
      - var X1
    * - X2
      - 1.0
      - -3.14
      - 3.14
      - unif
      - 1
      - 0.05
      - [-]
      - X2
      - None
      - 0
      - var X2
    * - X3
      - 1.0
      - -3.14
      - 3.14
      - unif
      - 1
      - 0.05
      - [-]
      - X3
      - None
      - 0
      - var X3
    * - X4
      - 1.0
      - -3.14
      - 3.14
      - unif
      - 1
      - 0.05
      - [-]
      - X4
      - None
      - 0
      - var X4
    * - X5
      - 1.0
      - -3.14
      - 3.14
      - unif
      - 1
      - 0.05
      - [-]
      - X5
      - None
      - 0
      - var X5
