
.. _meta_schemas-ach:

.. tabularcolumns:: | C | C |
.. list-table:: Metamoeling schemas
    :name: meta_schemas
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - Schema
      - Regressor types
    * - general
      - ID1, ID2, ID3, ID4, ID5, ID6
    * - general_fast
      - ID1, ID2, ID3, ID4, ID5, ID6
    * - general_fast_nonpol
      - ID1, ID2, ID3, ID4, ID6
    * - linear
      - ID1, ID2, ID3
    * - gaussian
      - ID4
    * - spline
      - ID5
    * - polynomial
      - ID6
    * - svr
      - ID7
    * - neural
      - ID8
