
.. _ML_models-ach:

.. tabularcolumns:: | C | C | C | C | C |
.. list-table:: ML models available
    :name: ML_models
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - ID
      - Type
      - ML model
      - Refs.
    * - ID1.1
      - linear regressors
      - LassoCV
      - :cite:`Shrinkage2016,Pedregosa2019`
    * - ID1.2
      - linear regressors
      - LassoLarsCV
      - :cite:`Iturbide2013,Pedregosa2019`
    * - ID1.3
      - linear regressors
      - ElasticNetCV
      - :cite:`Scholkopf2013,Pedregosa2019`
    * - ID1.4
      - linear regressors
      - LassoLarsIC
      - :cite:`Iturbide2013,Pedregosa2019`
    * - ID1.5
      - linear regressors
      - RidgeCV
      - :cite:`Scholkopf2013,Pedregosa2019`
    * - ID1.6
      - linear regressors
      - OrthogonalMatchingPursuitCV
      - :cite:`Saad2020,Pedregosa2019`
    * - ID2.1
      - outlier-robust regressors
      - HuberRegressor
      - :cite:`Owen2007,Pedregosa2019`
    * - ID3.1
      - bayesian regressors
      - ARDRegression
      - :cite:`MacKay1994,Pedregosa2019`
    * - ID3.2
      - bayesian regressors
      - BayesianRidge
      - :cite:`MacKay1992,Pedregosa2019`
    * - ID4.1
      - gaussian regressors
      - GaussianProcessRegressor
      - :cite:`Eberhard2000,Pedregosa2019`
    * - ID5.1
      - polynomial regressors
      - PolynomialLassoCV
      - :cite:`Lancaster1981,Myers2016,Pedregosa2019`
    * - ID5.2
      - polynomial regressors
      - PolynomialLassoLarsIC
      - :cite:`Lancaster1981,Myers2016,Pedregosa2019`
    * - ID5.3
      - polynomial regressors
      - PolynomialBayesianRidge
      - :cite:`Lancaster1981,Myers2016,Pedregosa2019`
    * - ID6.1
      - spline regressors
      - SplineLassoCV
      - :cite:`Myers2016,Pedregosa2019`
    * - ID6.2
      - spline regressors
      - SplineLassoLarsIC
      - :cite:`Myers2016,Pedregosa2019`
    * - ID6.3
      - spline regressors
      - SplineBayesianRidge
      - :cite:`Myers2016,Pedregosa2019`
    * - ID7.1
      -  svn regressor
      - LinearSVR
      - :cite:`Pedregosa2019`
    * - ID7.2
      -  svn regressor
      - SVR
      - :cite:`Pedregosa2019`
    * - ID8.1
      - neural regressor
      - MLPR
      - :cite:`Pedregosa2019`
