
.. _sampling_sens_sch-ach:

.. tabularcolumns:: | C | C | C | C |
.. list-table:: Sampling and sensitivity analysis available schemes
    :name: sampling_sens_sch
    :header-rows: 1
    :widths: auto
    :align: center
    :width: 100%
    :class: right-align-right-col align-cols left-align-left-col parse-table
    
    * - sensitivity method
      - Sampling method
      - Sensitivity method
      - Refs.
    * - Sobol
      - Saltelli sampling
      - Sobol sensitivity analysis
      - :cite:`SOBOL2001271,Saltelli2010,Campolongo2011a,Saltelli2002`
    * - Morris
      - Method of Morris
      - Morris Analysis
      - :cite:`Ruano2012,Campolongo2007,Morris1991`
    * - RBD-Fast
      - Latin hypercube sampling (LHS)
      - RBD-FAST - Random balance designs fourier amplitude sensitivity test
      - :cite:`McKay2000a,Iman1981,Tarantola2006,Plischke2010,Tissot2012`
    * - Fast
      - FAST - Fourier amplitude sensitivity test
      - Fourier amplitude sensitivity test model (eFAST)
      - :cite:`Cukier1973,Saltelli1999`
    * - Delta-MIM
      - Latin hypercube sampling (LHS)
      - Delta moment-independent measure
      - :cite:`McKay2000a,Iman1981,Borgonovo2007,Plischke2013`
    * - DGSM
      - Sampling for derivative-based global sensitivity measure (DGSM)
      - Derivative-based Global Sensitivity Measure (DGSM)
      - :cite:`Sobol2009,Sobol2010`
    * - Factorial
      - Fractional factorial sampling
      - Fractional factorial
      - :cite:`Saltelli2008`
    * - PAWN
      - Latin hypercube sampling (LHS)
      - PAWN sensitivity analysis
      - :cite:`Pianosi2015,Pianosi2018,Baroni2020`
