

.. _multi_3Dplot_XYZplt_case_1_Y_X2_X3-ach:
    
    .. figure:: ./images/multi_3Dplot_XYZplt_case_1_Y_X2_X3.jpg
        :alt: parse-figure
        :name: multi_3Dplot_XYZplt_case_1_Y_X2_X3
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Metamodels surface of variable X2 versus X3 versus Y in case_1. Tutorial A03
         
    .. raw:: latex

        \FloatBarrier
         
