

.. _multi_3Dplot_XYZplt_case_2_x_{max}_k_D-ach:
    
    .. figure:: ./images/multi_3Dplot_XYZplt_case_2_x_{max}_k_D.jpg
        :alt: parse-figure
        :name: multi_3Dplot_XYZplt_case_2_x_{max}_k_D
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Metamodels surface of variable :math:`k` versus :math:`D` versus :math:`x_{max}` in case_2. Tutorial A05
         
    .. raw:: latex

        \FloatBarrier
         
