

.. _multi_3Dplot_XYZplt_case_2_w_{damped}_m_E_{kin}-ach:
    
    .. figure:: ./images/multi_3Dplot_XYZplt_case_2_w_{damped}_m_E_{kin}.jpg
        :alt: parse-figure
        :name: multi_3Dplot_XYZplt_case_2_w_{damped}_m_E_{kin}
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Metamodels surface of variable :math:`m` versus :math:`E_{kin}` versus :math:`w_{damped}` in case_2. Tutorial A05
         
    .. raw:: latex

        \FloatBarrier
         
