

.. _multi_plot_XYplt_residuals_case_2_w_{damped}-ach:
    
    .. figure:: ./images/multi_plot_XYplt_residuals_case_2_w_{damped}.jpg
        :alt: parse-figure
        :name: multi_plot_XYplt_residuals_case_2_w_{damped}
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Sensitivity bar plot for case_1, :math:`w_{damped}`. Tutorial A05
         
    .. raw:: latex

        \FloatBarrier
         
