

.. _multi_plot_cross_X1_X2_case_0-ach:
    
    .. figure:: ./images/multi_plot_cross_X1_X2_case_0.jpg
        :alt: parse-figure
        :name: multi_plot_cross_X1_X2_case_0
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Cross represenation of variable X1 versus X2 in case_0. Tutorial A01
         
    .. raw:: latex

        \FloatBarrier
         
