

.. _multi_barplot_sensi_case_1_kursawe2-ach:
    
    .. figure:: ./images/multi_barplot_sensi_case_1_kursawe2.jpg
        :alt: parse-figure
        :name: multi_barplot_sensi_case_1_kursawe2
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Sensitivity bar plot for case_1, Kursawe function 2. Tutorial A04
         
    .. raw:: latex

        \FloatBarrier
         
