

.. _multi_plot_XYplt_residuals_case_1_Y-ach:
    
    .. figure:: ./images/multi_plot_XYplt_residuals_case_1_Y.jpg
        :alt: parse-figure
        :name: multi_plot_XYplt_residuals_case_1_Y
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Metamodels residual plot Y values versus predictions in case_1. Tutorial A03
         
    .. raw:: latex

        \FloatBarrier
         
