

.. _multi_3Dplot_XYZplt_case_1_kursawe2_X1_X2-ach:
    
    .. figure:: ./images/multi_3Dplot_XYZplt_case_1_kursawe2_X1_X2.jpg
        :alt: parse-figure
        :name: multi_3Dplot_XYZplt_case_1_kursawe2_X1_X2
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Metamodels surface of variable X1 versus X2 versus kursawe2 in case_1. Tutorial A04
         
    .. raw:: latex

        \FloatBarrier
         
