

.. _multi_plot_XYplt_residuals_case_1_kursawe2-ach:
    
    .. figure:: ./images/multi_plot_XYplt_residuals_case_1_kursawe2.jpg
        :alt: parse-figure
        :name: multi_plot_XYplt_residuals_case_1_kursawe2
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Metamodels residual plot Kursawe function 2 values versus predictions in case_1. Tutorial A04
         
    .. raw:: latex

        \FloatBarrier
         
