

.. _multi_plot_XYplt_residuals_case_2_x_{max}-ach:
    
    .. figure:: ./images/multi_plot_XYplt_residuals_case_2_x_{max}.jpg
        :alt: parse-figure
        :name: multi_plot_XYplt_residuals_case_2_x_{max}
        :align: center
        :figclass: parse-figure
        :scale: 20 %
         
        Sensitivity bar plot for case_2, :math:` x_{max}`. Tutorial A05
         
    .. raw:: latex

        \FloatBarrier
         
